imports:
    - php
    - javascript

filter:
    excluded_paths:
        - 'l10n/*'
        - 'js/jquery*'
        - 'js/bigshot*'

tools:
    php_analyzer:
        config:
            doc_comment_fixes:
                enabled:              true
