language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  global:
    - CORE_BRANCH=master
    - APP_NAME=gallery
  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

before_install:
  - composer self-update
  - composer install
  - composer require phpunit/phpcov:*
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
  - cd ../core
  - php occ app:enable $APP_NAME

script:
  # Test lint
  - cd apps/$APP_NAME
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '5.4' ]; then find . -name \*.php -print0 | xargs -0 -n 1 -P 4 php -l; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.4' ]; then find . -name \*.php -exec php -l "{}" \;; fi"

  # Run phpunit tests
  - phpunit -c phpunit.xml
  - phpunit -c phpunit.integration.xml

  # Merge clover reports
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php vendor/bin/phpcov merge --clover tests/clover.xml tests; fi;"

  # Create coverage report
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php ocular.phar code-coverage:upload --format=php-clover tests/clover.xml; fi"

matrix:
  include:
    - php: 5.4
      env: DB=mysql
    - php: 5.4
      env: DB=pgsql
    - php: 5.4
      env: "DB=mysql CORE_BRANCH=stable8.1"
  allow_failures:
    - php: hhvm
    - php: 7
  fast_finish: true
