language: php
php:
  - 5.4
  - 5.5

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

#before_install:
#  - cd ..
#  - git clone https://github.com/owncloud/core.git
#  - mv galleryplus core/apps/
#  - cd core
#  - git submodule init
#  - git submodule update
#  - cd apps/galleryplus

script: ant test
#  - phpunit tests
